name: CS5100-TA
channels:
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2023.01.10
  - certifi=2021.5.30
  - cycler=0.11.0
  - dill=0.3.4
  - freetype=2.12.1
  - icc_rt=2022.1.0
  - intel-openmp=2022.1.0
  - jpeg=9e
  - kiwisolver=1.3.1
  - lerc=3.0
  - libdeflate=1.8
  - libpng=1.6.37
  - libtiff=4.5.0
  - lz4-c=1.9.4
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1t
  - pillow=8.3.1
  - pip=21.2.2
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - python=3.6.13
  - python-dateutil=2.8.2
  - qt=5.9.7
  - scipy=1.5.2
  - setuptools=58.0.4
  - sip=4.19.8
  - six=1.16.0
  - sqlite=3.40.1
  - tk=8.6.12
  - tornado=6.1
  - wheel=0.37.1
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.5.2
